import AppKit

/// 剪贴历史的一条记录。
enum ClipSource { case dictation, copied }   // 本 app 转写 / 手动复制

struct ClipEntry {
    let text: String
    var source: ClipSource
    var time: Date
}

/// 最多 5 条的剪贴历史（纯内存、不落盘、退出即清，隐私优先）。
/// 两个来源：① 本 app 的转写结果 addFromApp；② 用户手动复制（轮询系统剪贴板）。
/// 自动去重：同样内容只留一条并置顶。跳过密码管理器标记的敏感/临时剪贴。
final class RecallStore {
    static let shared = RecallStore()

    private let maxCount = 5
    private(set) var entries: [ClipEntry] = []

    /// 历史变化时回调（AppDelegate 用来重绘菜单）。
    var onChange: (() -> Void)?

    // 自己写剪贴板时记录 changeCount，避免把自家写入又当成「手动复制」。
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var timer: Timer?

    // 密码管理器等会给剪贴打这些标记，遇到就跳过，不进历史。
    private let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    // MARK: 对外

    /// 本 app 产生的结果（转写 / 整理）：加进历史，来源 = dictation。
    func addFromApp(_ text: String) {
        add(text, source: .dictation)
        lastChangeCount = NSPasteboard.general.changeCount   // 若刚粘贴过，别再当手动复制收一遍
    }

    /// 开始轮询系统剪贴板：用户手动 copy 的内容进历史，来源 = copied。
    func startMonitoring() {
        lastChangeCount = NSPasteboard.general.changeCount
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    /// 点击某条 → 复制回剪贴板并置顶。
    func recall(byText text: String) {
        Paster.copy(text)
        lastChangeCount = NSPasteboard.general.changeCount
        if let i = entries.firstIndex(where: { $0.text == text }) {
            let e = entries.remove(at: i); entries.insert(e, at: 0)
        }
        onChange?()
    }

    // MARK: 内部

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        // 跳过敏感/临时剪贴（密码管理器等）
        if let types = pb.types, types.contains(where: { skipTypes.contains($0.rawValue) }) { return }
        guard let s = pb.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines),
              !s.isEmpty else { return }
        add(s, source: .copied)
    }

    private func add(_ text: String, source: ClipSource) {
        let t = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !t.isEmpty else { return }
        if let i = entries.firstIndex(where: { $0.text == t }) {
            // 去重：置顶、更新时间；本 app 来源优先覆盖（转写胜过复制）
            var e = entries.remove(at: i)
            e.time = Date()
            if source == .dictation { e.source = .dictation }
            entries.insert(e, at: 0)
        } else {
            entries.insert(ClipEntry(text: t, source: source, time: Date()), at: 0)
            if entries.count > maxCount { entries.removeLast() }
        }
        onChange?()
    }
}
